### ISSUE TITLE
Brokes cursor after reverting

### ISSUE THREAD

**Issue by YAUIO** [ShikkesoraSIM/anti-mindblock#1]
set osu folder, selected skin, then rotate numbers -> refresh skin
reset numbers -> refresh skin

should be red static cursor w/o cursortrail
and after resetting numbers it becomes white with red trail

https://mega.nz/file/SyZmjAhC#eeEkd7_Z22xaujjLznIaFgC01homhcVgKFh_MAMboKQ skin link

**Comment by ShikkesoraSIM** [comment]
Should be half resolved in new update, thanks!
