### ISSUE TITLE
break the ingame numbers

### ISSUE THREAD

**Issue by Kuina-chan** [ShikkesoraSIM/anti-mindblock#15]
![screenshot087](https://github.com/ShikkesoraSIM/anti-mindblock/assets/75318520/efc03c01-6660-4d2c-991d-0a35081cc2eb)
The score and the accuracy is completely broken, even after I pressed restore number

**Comment by ShikkesoraSIM** [comment]
Hello, this is a know issue. This happens if theres subfolders in your skin.
