### ISSUE TITLE
Skin elements within folders are changed to the most recently found file of the same name.

### ISSUE THREAD

**Issue by Coppertine** [ShikkesoraSIM/anti-mindblock#2]
Skin: IJN Yamashiro V2
Essentially, theres a folder which holds different skin elements that you can replace depending on taste (found in `Configuration` folder). However, all instances of a skin element (i.e. `scorebar-bg.png`) is replaced with the more recently found one, (in this case, the scorebar with a background, which is not intended and should only affect those on the top level and not any additional files within)

Images found within folders within a skin folder should not be touched and instead, images that are affected should have a backup folder created so that the user can figure out what is changed and what is to be replaced once reverting.

**Comment by ShikkesoraSIM** [comment]
Thanks for reporting! 
This is a known issue, I'm working on it but might take a bit to get fixed :)

**Comment by ShikkesoraSIM** [comment]
Should be half resolved in new update, thanks!
