### ISSUE TITLE
Rotate Numbers button still works even before restoring the numbers. Flips the images twice and causes some files to be permanently replaced.

### ISSUE THREAD

**Issue by YotGun** [ShikkesoraSIM/anti-mindblock#4]
Clicking "**Rotate Numbers**" twice will flip everything again including the "**temp_australia_mode**" folder. This seems to be unintended behaviour since the code "_if is_australia_mode_active:_" in the function "**activate_australia_mode()**" should be blocking it from even running. Clicking restore after this will keep the final skin state in a rotated mode. (Files that ended up being replaced with a transparent png are unrecoverable as a result of this process)

Suggestions on the fixes:

- Instead of keeping the states in a global variable, this should be written into a config file. A restart of the program will not break the code unlike now, where the global variables are going to reset on every startup of the file. Maybe reading and writing to a json dictionary file might be easier and make the code easier to work with in the future where more features are planned.
- A whole backup of the skin might be preferred instead of the "**temp_australia_mode**" folder as unintended interactions might break the skin. If someone doesn't have a backup, its going to be a pain to recover.

This is a really nice program and I appreciate the effort you put into the osu! community. :D

**Comment by ShikkesoraSIM** [comment]
Should be half resolved in new update, thanks!
