### ISSUE TITLE
Tablet area rotation not rotating well.

### ISSUE THREAD

**Issue by bxnn** [ShikkesoraSIM/anti-mindblock#6]
The program works perfectly fine to rotate the area by 180 degrees when you're using your tablet normally, but if you use already a 180 degrees rotated area because you like the cable of the tablet to be the other side, the program will try to set from 180 degrees to 180 degrees. You could add something that rotates it to 0 degrees if it is already to 180 degrees ! 
Thanks!

**Comment by ShikkesoraSIM** [comment]
Hello! How is this a problem for you? I also play with my tablet rotated and the program is made to turn it upside down no matter what degree is initially set. Did you check the "Known bugs" list on the last release, and made sure that its not just something about the first launch?

**Comment by bxnn** [comment]
whoops my OTD was glitched it works fine after I checked it sorry for the confusion ^^
