### ISSUE TITLE
after it reverse it back

### ISSUE THREAD

**Issue by Miyuki-10** [ShikkesoraSIM/anti-mindblock#8]
after reverse it back, i cannot see accuracy or score.

**Comment by ShikkesoraSIM** [comment]
Please read the known issues
![image](https://github.com/ShikkesoraSIM/anti-mindblock/assets/148418529/7e3b5496-95fe-48e0-847c-1d5f4afd6995)
To make sure this things don't happen make sure that the skin you're using doesn't have like a bunch of subfolders and backup files everywhere, my program still gets confused at that but will get fixed soon, I'm working on it now
